spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yubaby?useUnicode=true&characterEncoding=utf8&useSSL=false&setTimeZone
    username: root
    password: java1998
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 60MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/yubaby
  redis:
    url: redis://localhost:6379
  mail:
    host: smtp.163.com
    username: username
    password: password
    protocol: smtps
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  mapper-locations: classpath:mappers/*/*.xml
server:
  port: 8090